version: '3.4'

services:
  postgres:
    container_name: "mypostgres"
    image: postgres:latest
    restart: always
    build: .
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: board