@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhbGV5LXRlc3QiLCJpYXQiOjE3MDgzNTA1ODcsImV4cCI6MTcwODM1NDE4N30.0CljVoK5dD3CyTY-TkyVUs-hcu5Q5ASrMp5sHP2PaZc
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhbGV5LXRlc3QxIiwiaWF0IjoxNzA4MzUxNzk5LCJleHAiOjE3MDgzNTUzOTl9.iJauOlM2aD_eu10EPyyap44_2b6YpzOtZq8nLxFL3zE
### create board
POST http://localhost:3000/boards HTTP/1.1
Authorization: Bearer {{token2}}
content-type: application/json

{
    "title": "haley test 2 가 만든 게시물 입니다",
    "description": "내용3423432"
}

### get boards
GET http://localhost:3000/boards HTTP/1.1
Authorization: Bearer {{token2}}

### delete board by id
DELETE http://localhost:3000/boards/6 HTTP/1.1
Authorization: Bearer {{token2}}

### update board status
PATCH http://localhost:3000/boards/2/status HTTP/1.1
Content-Type: application/json

{
    "status": "private"
}
